### ISSUE TITLE
Using this library I am getting proper client ssl certificate was not presented

### ISSUE THREAD

**Issue by FSchmitthammer** [adplabs/adp-connection-NET#18]
I am getting the error "proper client ssl certificate was not presented".  If I use the same cert and key with postman it works fine.  Below is my config:

![image](https://user-images.githubusercontent.com/17108448/55256578-94c3d480-521a-11e9-8f39-62689cbcd4c3.png)

Please advise how to correct this issue.

**Comment by mdresch** [comment]
Dear FSchmitthammer, 
I have been reading these library requests from some time now. And I am able to assist you with these certificates by now. Please ADP could you please be so kind not to have these posts in the public domain. The client ID en Client Secret plus the methodes used to connect in the end seem easy to support but are not information details which should be shared in the public domain. Could these be removed or instructions to how a support ticket is created be moved to the adp systems?
Kind Regards, Menno

**Comment by FSchmitthammer** [comment]
Menno,

I appreciate the answer.  I covered my client id and my client secret for that reason.  However, I do need help with this library.  Is this the place to ask questions about this library?  My marketplace support person says it is not broken and I need to figure it out.  However, I am using the library they supplied!

Please let me know a better place to ask such questions about this library.

Regards,

Fred

**Comment by mdresch** [comment]
Dear Fred,

I have been so excited to see ADP labs to Github and was so glad to see some of the repositories which where made available. However I was also kind of scared Client credentials where used when asking for support.

I am not the person to provide support with regards to the connectivity and which ssl certificates are to be used. But because I do see them come by from time to time I would like to see these questions go to the marketplace behind the login credentials instead of the public domain.

When I would pretend to provide you support and pretend I would know exactly which actions to take including you providing me with the server certificates. To me is a nightmare and would like to see these not appear in the public domain. I do understand the client key is crossed and does not show but I would also like to see an ADP employee to support you properly.

I hope you will receive a good support with your certificate questions and hope to see these questions not to rise in the public domain in future.

Kind Regards, Menno

**Comment by mdresch** [comment]
https://developers.adp.com/articles/guides/authorization-process-end-user-apps

**Comment by FSchmitthammer** [comment]
I  have confirmed that CURL is getting the same result.  I really need to get this addressed.  Anybody have this same issue and have a resolution?

**Comment by ADPMarketplace** [comment]
Hi,
I see that you're using .pem file along with .key file. Could you please generate a .pfx file and then use it along with .key file as mentioned in the .Net library.

"sslCertPath"":    ""~/Content/certs/apiclient_iat.pfx",
"sslKeyPath"":     ""~/Content/certs/apiclient_iat.key",

Use the below command to generate .pfx file.

Command:
openssl pkcs12 -inkey key_file.key -in pem_file.pem -export -out pfx_file.pfx


Thanks,
Mahesh

**Comment by FSchmitthammer** [comment]
Thank you!  This works now.  We can close this.
Regards,
Fred Schmitthammer
(562)307-0219
(623)258-4400

**Comment by ADPMarketplace** [comment]
Hi,
Thank you for letting us know.

Thanks,
Mahesh

**Comment by parasagrawal71** [comment]
Hi,
I am getting the same issue in the react js application, so can generating pfx will work here too?

Using httpsAgent with 'pem' and 'key' files in the node environment work fine.
But in react application it's throwing me the same error "proper client SSL certificate was not presented" in spite of providing pem and key files in httpsAgent.

**Comment by abhishekkandi** [comment]
@ADPMarketplace We've recently generated a new PEM & PRIVATEKEY via self-service portal.
But while generating PFX using below command. It is prompting for EXPORT PASSWORD ?
Any idea about it ?

openssl pkcs12 -inkey key_file.key -in pem_file.pem -export -out pfx_file.pfx
