### ISSUE TITLE
proper client ssl certificate was not presented

### ISSUE THREAD

**Issue by Chandakmanish04** [adplabs/adp-connection-NET#27]
We are using latest code to query ADP API for production, getting below error:

{
  "error": "invalid_request",
  "error_description": "proper client ssl certificate was not presented"
}

Below are some of the more details:

HTTP/1.1 401 Unauthorized
ADP-CorrelationID: a81b72be-bb57-4f1b-8106-0e617d1c1049
Pragma: no-cache
Cache-Control: no-store, no-cache, private
Content-Type: application/json;charset=UTF-8
Content-Length: 106
Date: Fri, 17 Jan 2020 10:05:37 GMT
Server: ADP API

We tried same thing using Postman with ClientId and Client Secret, facing same issue there with error:
error: "invalid_request"
error_description: "proper client ssl certificate was not presented"

**Comment by ADPMarketplace** [comment]
Hi,

We see below logs in our system. Your certificate org name and CAR org name is not matching due to which you are receiving below error.

2020-01-17T02:50:37.922-0500 WARNING 3312138 com.l7tech.server.policy.assertion.ServerAuditDetailAssertion: -5: (Policy for service #e001cfd0c1c1ffaa18e187b5e72fdd38, auth/oauth/v2/token:99) CERTFAIL certificate_org='First Foundation', client_org='FIRST FOUNDATION BANK', client_ident='af3a1a7d-547b-4c5a-bca4-c819f0af82ac', errormsg='Failed org check and is not on whitelist'

Thanks,
Sruthi

**Comment by Chandakmanish04** [comment]
To resolve this who would be contact person

**Comment by ADPMarketplace** [comment]
Hi,

Please reach out to your ADP Account Representative who has provided you with client credentials for accessing APIs for assisting you with this issue.

Thanks,
Kirthi.
